using System;
using System.Reflection;

namespace Visual
{
#region Enumeration helpers
    public class RequestValue : Attribute
    {
        public string Value;

        public RequestValue(string AValue)
        {
            Value = AValue;
        }
    }

    public class RequestValues
    {
        public static string Get(Enum Enumerator)
        {
            Type EnumeratorType = Enumerator.GetType();
            MemberInfo[] MemberInfo = EnumeratorType.GetMember(Enumerator.ToString());

            if ((MemberInfo != null) && (MemberInfo.Length > 0))
            {
                object[] MemberAttributes = MemberInfo[0].GetCustomAttributes(typeof(RequestValue), false);
                if ((MemberAttributes != null) && (MemberAttributes.Length > 0)) return ((RequestValue)MemberAttributes[0]).Value;
            }

            return Enumerator.ToString();
        }
    }
#endregion

    public enum Timezone
    {
        [RequestValue("Africa/Abidjan")]
        Africa_Abidjan,
        [RequestValue("Africa/Accra")]
        Africa_Accra,
        [RequestValue("Africa/Addis_Ababa")]
        Africa_Addis_Ababa,
        [RequestValue("Africa/Algiers")]
        Africa_Algiers,
        [RequestValue("Africa/Asmera")]
        Africa_Asmera,
        [RequestValue("Africa/Bamako")]
        Africa_Bamako,
        [RequestValue("Africa/Bangui")]
        Africa_Bangui,
        [RequestValue("Africa/Banjul")]
        Africa_Banjul,
        [RequestValue("Africa/Bissau")]
        Africa_Bissau,
        [RequestValue("Africa/Blantyre")]
        Africa_Blantyre,
        [RequestValue("Africa/Brazzaville")]
        Africa_Brazzaville,
        [RequestValue("Africa/Bujumbura")]
        Africa_Bujumbura,
        [RequestValue("Africa/Cairo")]
        Africa_Cairo,
        [RequestValue("Africa/Casablanca")]
        Africa_Casablanca,
        [RequestValue("Africa/Ceuta")]
        Africa_Ceuta,
        [RequestValue("Africa/Conakry")]
        Africa_Conakry,
        [RequestValue("Africa/Dakar")]
        Africa_Dakar,
        [RequestValue("Africa/Dar_es_Salaam")]
        Africa_Dar_es_Salaam,
        [RequestValue("Africa/Djibouti")]
        Africa_Djibouti,
        [RequestValue("Africa/Douala")]
        Africa_Douala,
        [RequestValue("Africa/El_Aaiun")]
        Africa_El_Aaiun,
        [RequestValue("Africa/Freetown")]
        Africa_Freetown,
        [RequestValue("Africa/Gaborone")]
        Africa_Gaborone,
        [RequestValue("Africa/Harare")]
        Africa_Harare,
        [RequestValue("Africa/Johannesburg")]
        Africa_Johannesburg,
        [RequestValue("Africa/Kampala")]
        Africa_Kampala,
        [RequestValue("Africa/Khartoum")]
        Africa_Khartoum,
        [RequestValue("Africa/Kigali")]
        Africa_Kigali,
        [RequestValue("Africa/Kinshasa")]
        Africa_Kinshasa,
        [RequestValue("Africa/Lagos")]
        Africa_Lagos,
        [RequestValue("Africa/Libreville")]
        Africa_Libreville,
        [RequestValue("Africa/Lome")]
        Africa_Lome,
        [RequestValue("Africa/Luanda")]
        Africa_Luanda,
        [RequestValue("Africa/Lubumbashi")]
        Africa_Lubumbashi,
        [RequestValue("Africa/Lusaka")]
        Africa_Lusaka,
        [RequestValue("Africa/Malabo")]
        Africa_Malabo,
        [RequestValue("Africa/Maputo")]
        Africa_Maputo,
        [RequestValue("Africa/Maseru")]
        Africa_Maseru,
        [RequestValue("Africa/Mbabane")]
        Africa_Mbabane,
        [RequestValue("Africa/Mogadishu")]
        Africa_Mogadishu,
        [RequestValue("Africa/Monrovia")]
        Africa_Monrovia,
        [RequestValue("Africa/Nairobi")]
        Africa_Nairobi,
        [RequestValue("Africa/Ndjamena")]
        Africa_Ndjamena,
        [RequestValue("Africa/Niamey")]
        Africa_Niamey,
        [RequestValue("Africa/Nouakchott")]
        Africa_Nouakchott,
        [RequestValue("Africa/Ouagadougou")]
        Africa_Ouagadougou,
        [RequestValue("Africa/Porto-Novo")]
        Africa_PortoNovo,
        [RequestValue("Africa/Sao_Tome")]
        Africa_Sao_Tome,
        [RequestValue("Africa/Timbuktu")]
        Africa_Timbuktu,
        [RequestValue("Africa/Tripoli")]
        Africa_Tripoli,
        [RequestValue("Africa/Tunis")]
        Africa_Tunis,
        [RequestValue("Africa/Windhoek")]
        Africa_Windhoek,
        [RequestValue("America/Adak")]
        America_Adak,
        [RequestValue("America/Anchorage")]
        America_Anchorage,
        [RequestValue("America/Anguilla")]
        America_Anguilla,
        [RequestValue("America/Antigua")]
        America_Antigua,
        [RequestValue("America/Araguaina")]
        America_Araguaina,
        [RequestValue("America/Aruba")]
        America_Aruba,
        [RequestValue("America/Asuncion")]
        America_Asuncion,
        [RequestValue("America/Atka")]
        America_Atka,
        [RequestValue("America/Barbados")]
        America_Barbados,
        [RequestValue("America/Belem")]
        America_Belem,
        [RequestValue("America/Belize")]
        America_Belize,
        [RequestValue("America/Boa_Vista")]
        America_Boa_Vista,
        [RequestValue("America/Bogota")]
        America_Bogota,
        [RequestValue("America/Boise")]
        America_Boise,
        [RequestValue("America/Buenos_Aires")]
        America_Buenos_Aires,
        [RequestValue("America/Cambridge_Bay")]
        America_Cambridge_Bay,
        [RequestValue("America/Cancun")]
        America_Cancun,
        [RequestValue("America/Caracas")]
        America_Caracas,
        [RequestValue("America/Catamarca")]
        America_Catamarca,
        [RequestValue("America/Cayenne")]
        America_Cayenne,
        [RequestValue("America/Cayman")]
        America_Cayman,
        [RequestValue("America/Chicago")]
        America_Chicago,
        [RequestValue("America/Chihuahua")]
        America_Chihuahua,
        [RequestValue("America/Cordoba")]
        America_Cordoba,
        [RequestValue("America/Costa_Rica")]
        America_Costa_Rica,
        [RequestValue("America/Cuiaba")]
        America_Cuiaba,
        [RequestValue("America/Curacao")]
        America_Curacao,
        [RequestValue("America/Dawson")]
        America_Dawson,
        [RequestValue("America/Dawson_Creek")]
        America_Dawson_Creek,
        [RequestValue("America/Denver")]
        America_Denver,
        [RequestValue("America/Detroit")]
        America_Detroit,
        [RequestValue("America/Dominica")]
        America_Dominica,
        [RequestValue("America/Edmonton")]
        America_Edmonton,
        [RequestValue("America/El_Salvador")]
        America_El_Salvador,
        [RequestValue("America/Ensenada")]
        America_Ensenada,
        [RequestValue("America/Fort_Wayne")]
        America_Fort_Wayne,
        [RequestValue("America/Fortaleza")]
        America_Fortaleza,
        [RequestValue("America/Glace_Bay")]
        America_Glace_Bay,
        [RequestValue("America/Godthab")]
        America_Godthab,
        [RequestValue("America/Goose_Bay")]
        America_Goose_Bay,
        [RequestValue("America/Grand_Turk")]
        America_Grand_Turk,
        [RequestValue("America/Grenada")]
        America_Grenada,
        [RequestValue("America/Guadeloupe")]
        America_Guadeloupe,
        [RequestValue("America/Guatemala")]
        America_Guatemala,
        [RequestValue("America/Guayaquil")]
        America_Guayaquil,
        [RequestValue("America/Guyana")]
        America_Guyana,
        [RequestValue("America/Halifax")]
        America_Halifax,
        [RequestValue("America/Havana")]
        America_Havana,
        [RequestValue("America/Hermosillo")]
        America_Hermosillo,
        [RequestValue("America/Indiana/Indianapolis")]
        America_Indiana_Indianapolis,
        [RequestValue("America/Indiana/Knox")]
        America_Indiana_Knox,
        [RequestValue("America/Indiana/Marengo")]
        America_Indiana_Marengo,
        [RequestValue("America/Indiana/Vevay")]
        America_Indiana_Vevay,
        [RequestValue("America/Indianapolis")]
        America_Indianapolis,
        [RequestValue("America/Inuvik")]
        America_Inuvik,
        [RequestValue("America/Iqaluit")]
        America_Iqaluit,
        [RequestValue("America/Jamaica")]
        America_Jamaica,
        [RequestValue("America/Jujuy")]
        America_Jujuy,
        [RequestValue("America/Juneau")]
        America_Juneau,
        [RequestValue("America/Kentucky/Louisville")]
        America_Kentucky_Louisville,
        [RequestValue("America/Kentucky/Monticello")]
        America_Kentucky_Monticello,
        [RequestValue("America/Knox_IN")]
        America_Knox_IN,
        [RequestValue("America/La_Paz")]
        America_La_Paz,
        [RequestValue("America/Lima")]
        America_Lima,
        [RequestValue("America/Los_Angeles")]
        America_Los_Angeles,
        [RequestValue("America/Louisville")]
        America_Louisville,
        [RequestValue("America/Maceio")]
        America_Maceio,
        [RequestValue("America/Managua")]
        America_Managua,
        [RequestValue("America/Manaus")]
        America_Manaus,
        [RequestValue("America/Martinique")]
        America_Martinique,
        [RequestValue("America/Mazatlan")]
        America_Mazatlan,
        [RequestValue("America/Mendoza")]
        America_Mendoza,
        [RequestValue("America/Menominee")]
        America_Menominee,
        [RequestValue("America/Merida")]
        America_Merida,
        [RequestValue("America/Mexico_City")]
        America_Mexico_City,
        [RequestValue("America/Miquelon")]
        America_Miquelon,
        [RequestValue("America/Monterrey")]
        America_Monterrey,
        [RequestValue("America/Montevideo")]
        America_Montevideo,
        [RequestValue("America/Montreal")]
        America_Montreal,
        [RequestValue("America/Montserrat")]
        America_Montserrat,
        [RequestValue("America/Nassau")]
        America_Nassau,
        [RequestValue("America/New_York")]
        America_New_York,
        [RequestValue("America/Nipigon")]
        America_Nipigon,
        [RequestValue("America/Nome")]
        America_Nome,
        [RequestValue("America/Noronha")]
        America_Noronha,
        [RequestValue("America/Panama")]
        America_Panama,
        [RequestValue("America/Pangnirtung")]
        America_Pangnirtung,
        [RequestValue("America/Paramaribo")]
        America_Paramaribo,
        [RequestValue("America/Phoenix")]
        America_Phoenix,
        [RequestValue("America/Port-au-Prince")]
        America_PortauPrince,
        [RequestValue("America/Port_of_Spain")]
        America_Port_of_Spain,
        [RequestValue("America/Porto_Acre")]
        America_Porto_Acre,
        [RequestValue("America/Porto_Velho")]
        America_Porto_Velho,
        [RequestValue("America/Puerto_Rico")]
        America_Puerto_Rico,
        [RequestValue("America/Rainy_River")]
        America_Rainy_River,
        [RequestValue("America/Rankin_Inlet")]
        America_Rankin_Inlet,
        [RequestValue("America/Regina")]
        America_Regina,
        [RequestValue("America/Rosario")]
        America_Rosario,
        [RequestValue("America/Santiago")]
        America_Santiago,
        [RequestValue("America/Santo_Domingo")]
        America_Santo_Domingo,
        [RequestValue("America/Sao_Paulo")]
        America_Sao_Paulo,
        [RequestValue("America/Scoresbysund")]
        America_Scoresbysund,
        [RequestValue("America/Shiprock")]
        America_Shiprock,
        [RequestValue("America/St_Johns")]
        America_St_Johns,
        [RequestValue("America/St_Kitts")]
        America_St_Kitts,
        [RequestValue("America/St_Lucia")]
        America_St_Lucia,
        [RequestValue("America/St_Thomas")]
        America_St_Thomas,
        [RequestValue("America/St_Vincent")]
        America_St_Vincent,
        [RequestValue("America/Swift_Current")]
        America_Swift_Current,
        [RequestValue("America/Tegucigalpa")]
        America_Tegucigalpa,
        [RequestValue("America/Thule")]
        America_Thule,
        [RequestValue("America/Thunder_Bay")]
        America_Thunder_Bay,
        [RequestValue("America/Tijuana")]
        America_Tijuana,
        [RequestValue("America/Tortola")]
        America_Tortola,
        [RequestValue("America/Vancouver")]
        America_Vancouver,
        [RequestValue("America/Virgin")]
        America_Virgin,
        [RequestValue("America/Whitehorse")]
        America_Whitehorse,
        [RequestValue("America/Winnipeg")]
        America_Winnipeg,
        [RequestValue("America/Yakutat")]
        America_Yakutat,
        [RequestValue("America/Yellowknife")]
        America_Yellowknife,
        [RequestValue("Antarctica/Casey")]
        Antarctica_Casey,
        [RequestValue("Antarctica/Davis")]
        Antarctica_Davis,
        [RequestValue("Antarctica/DumontDUrville")]
        Antarctica_DumontDUrville,
        [RequestValue("Antarctica/Mawson")]
        Antarctica_Mawson,
        [RequestValue("Antarctica/McMurdo")]
        Antarctica_McMurdo,
        [RequestValue("Antarctica/Palmer")]
        Antarctica_Palmer,
        [RequestValue("Antarctica/South_Pole")]
        Antarctica_South_Pole,
        [RequestValue("Antarctica/Syowa")]
        Antarctica_Syowa,
        [RequestValue("Arctic/Longyearbyen")]
        Arctic_Longyearbyen,
        [RequestValue("Asia/Aden")]
        Asia_Aden,
        [RequestValue("Asia/Almaty")]
        Asia_Almaty,
        [RequestValue("Asia/Amman")]
        Asia_Amman,
        [RequestValue("Asia/Anadyr")]
        Asia_Anadyr,
        [RequestValue("Asia/Aqtau")]
        Asia_Aqtau,
        [RequestValue("Asia/Aqtobe")]
        Asia_Aqtobe,
        [RequestValue("Asia/Ashgabat")]
        Asia_Ashgabat,
        [RequestValue("Asia/Ashkhabad")]
        Asia_Ashkhabad,
        [RequestValue("Asia/Baghdad")]
        Asia_Baghdad,
        [RequestValue("Asia/Bahrain")]
        Asia_Bahrain,
        [RequestValue("Asia/Baku")]
        Asia_Baku,
        [RequestValue("Asia/Bangkok")]
        Asia_Bangkok,
        [RequestValue("Asia/Beirut")]
        Asia_Beirut,
        [RequestValue("Asia/Bishkek")]
        Asia_Bishkek,
        [RequestValue("Asia/Brunei")]
        Asia_Brunei,
        [RequestValue("Asia/Calcutta")]
        Asia_Calcutta,
        [RequestValue("Asia/Chungking")]
        Asia_Chungking,
        [RequestValue("Asia/Colombo")]
        Asia_Colombo,
        [RequestValue("Asia/Dacca")]
        Asia_Dacca,
        [RequestValue("Asia/Damascus")]
        Asia_Damascus,
        [RequestValue("Asia/Dili")]
        Asia_Dili,
        [RequestValue("Asia/Dubai")]
        Asia_Dubai,
        [RequestValue("Asia/Dushanbe")]
        Asia_Dushanbe,
        [RequestValue("Asia/Gaza")]
        Asia_Gaza,
        [RequestValue("Asia/Harbin")]
        Asia_Harbin,
        [RequestValue("Asia/Hong_Kong")]
        Asia_Hong_Kong,
        [RequestValue("Asia/Hovd")]
        Asia_Hovd,
        [RequestValue("Asia/Irkutsk")]
        Asia_Irkutsk,
        [RequestValue("Asia/Istanbul")]
        Asia_Istanbul,
        [RequestValue("Asia/Jakarta")]
        Asia_Jakarta,
        [RequestValue("Asia/Jayapura")]
        Asia_Jayapura,
        [RequestValue("Asia/Jerusalem")]
        Asia_Jerusalem,
        [RequestValue("Asia/Kabul")]
        Asia_Kabul,
        [RequestValue("Asia/Kamchatka")]
        Asia_Kamchatka,
        [RequestValue("Asia/Karachi")]
        Asia_Karachi,
        [RequestValue("Asia/Kashgar")]
        Asia_Kashgar,
        [RequestValue("Asia/Katmandu")]
        Asia_Katmandu,
        [RequestValue("Asia/Krasnoyarsk")]
        Asia_Krasnoyarsk,
        [RequestValue("Asia/Kuala_Lumpur")]
        Asia_Kuala_Lumpur,
        [RequestValue("Asia/Kuching")]
        Asia_Kuching,
        [RequestValue("Asia/Kuwait")]
        Asia_Kuwait,
        [RequestValue("Asia/Macao")]
        Asia_Macao,
        [RequestValue("Asia/Magadan")]
        Asia_Magadan,
        [RequestValue("Asia/Manila")]
        Asia_Manila,
        [RequestValue("Asia/Muscat")]
        Asia_Muscat,
        [RequestValue("Asia/Nicosia")]
        Asia_Nicosia,
        [RequestValue("Asia/Novosibirsk")]
        Asia_Novosibirsk,
        [RequestValue("Asia/Omsk")]
        Asia_Omsk,
        [RequestValue("Asia/Phnom_Penh")]
        Asia_Phnom_Penh,
        [RequestValue("Asia/Pyongyang")]
        Asia_Pyongyang,
        [RequestValue("Asia/Qatar")]
        Asia_Qatar,
        [RequestValue("Asia/Rangoon")]
        Asia_Rangoon,
        [RequestValue("Asia/Riyadh")]
        Asia_Riyadh,
        [RequestValue("Asia/Riyadh87")]
        Asia_Riyadh87,
        [RequestValue("Asia/Riyadh88")]
        Asia_Riyadh88,
        [RequestValue("Asia/Riyadh89")]
        Asia_Riyadh89,
        [RequestValue("Asia/Saigon")]
        Asia_Saigon,
        [RequestValue("Asia/Samarkand")]
        Asia_Samarkand,
        [RequestValue("Asia/Seoul")]
        Asia_Seoul,
        [RequestValue("Asia/Shanghai")]
        Asia_Shanghai,
        [RequestValue("Asia/Singapore")]
        Asia_Singapore,
        [RequestValue("Asia/Taipei")]
        Asia_Taipei,
        [RequestValue("Asia/Tashkent")]
        Asia_Tashkent,
        [RequestValue("Asia/Tbilisi")]
        Asia_Tbilisi,
        [RequestValue("Asia/Tehran")]
        Asia_Tehran,
        [RequestValue("Asia/Tel_Aviv")]
        Asia_Tel_Aviv,
        [RequestValue("Asia/Thimbu")]
        Asia_Thimbu,
        [RequestValue("Asia/Thimphu")]
        Asia_Thimphu,
        [RequestValue("Asia/Tokyo")]
        Asia_Tokyo,
        [RequestValue("Asia/Ujung_Pandang")]
        Asia_Ujung_Pandang,
        [RequestValue("Asia/Ulaanbaatar")]
        Asia_Ulaanbaatar,
        [RequestValue("Asia/Ulan_Bator")]
        Asia_Ulan_Bator,
        [RequestValue("Asia/Urumqi")]
        Asia_Urumqi,
        [RequestValue("Asia/Vientiane")]
        Asia_Vientiane,
        [RequestValue("Asia/Vladivostok")]
        Asia_Vladivostok,
        [RequestValue("Asia/Yakutsk")]
        Asia_Yakutsk,
        [RequestValue("Asia/Yekaterinburg")]
        Asia_Yekaterinburg,
        [RequestValue("Asia/Yerevan")]
        Asia_Yerevan,
        [RequestValue("Atlantic/Azores")]
        Atlantic_Azores,
        [RequestValue("Atlantic/Bermuda")]
        Atlantic_Bermuda,
        [RequestValue("Atlantic/Canary")]
        Atlantic_Canary,
        [RequestValue("Atlantic/Cape_Verde")]
        Atlantic_Cape_Verde,
        [RequestValue("Atlantic/Faeroe")]
        Atlantic_Faeroe,
        [RequestValue("Atlantic/Jan_Mayen")]
        Atlantic_Jan_Mayen,
        [RequestValue("Atlantic/Madeira")]
        Atlantic_Madeira,
        [RequestValue("Atlantic/Reykjavik")]
        Atlantic_Reykjavik,
        [RequestValue("Atlantic/South_Georgia")]
        Atlantic_South_Georgia,
        [RequestValue("Atlantic/St_Helena")]
        Atlantic_St_Helena,
        [RequestValue("Atlantic/Stanley")]
        Atlantic_Stanley,
        [RequestValue("Australia/ACT")]
        Australia_ACT,
        [RequestValue("Australia/Adelaide")]
        Australia_Adelaide,
        [RequestValue("Australia/Brisbane")]
        Australia_Brisbane,
        [RequestValue("Australia/Broken_Hill")]
        Australia_Broken_Hill,
        [RequestValue("Australia/Canberra")]
        Australia_Canberra,
        [RequestValue("Australia/Darwin")]
        Australia_Darwin,
        [RequestValue("Australia/Hobart")]
        Australia_Hobart,
        [RequestValue("Australia/LHI")]
        Australia_LHI,
        [RequestValue("Australia/Lindeman")]
        Australia_Lindeman,
        [RequestValue("Australia/Lord_Howe")]
        Australia_Lord_Howe,
        [RequestValue("Australia/Melbourne")]
        Australia_Melbourne,
        [RequestValue("Australia/NSW")]
        Australia_NSW,
        [RequestValue("Australia/North")]
        Australia_North,
        [RequestValue("Australia/Perth")]
        Australia_Perth,
        [RequestValue("Australia/Queensland")]
        Australia_Queensland,
        [RequestValue("Australia/South")]
        Australia_South,
        [RequestValue("Australia/Sydney")]
        Australia_Sydney,
        [RequestValue("Australia/Tasmania")]
        Australia_Tasmania,
        [RequestValue("Australia/Victoria")]
        Australia_Victoria,
        [RequestValue("Australia/West")]
        Australia_West,
        [RequestValue("Australia/Yancowinna")]
        Australia_Yancowinna,
        [RequestValue("Brazil/Acre")]
        Brazil_Acre,
        [RequestValue("Brazil/DeNoronha")]
        Brazil_DeNoronha,
        [RequestValue("Brazil/East")]
        Brazil_East,
        [RequestValue("Brazil/West")]
        Brazil_West,
        [RequestValue("CET")]
        CET,
        [RequestValue("CST6CDT")]
        CST6CDT,
        [RequestValue("Canada/Atlantic")]
        Canada_Atlantic,
        [RequestValue("Canada/Central")]
        Canada_Central,
        [RequestValue("Canada/East-Saskatchewan")]
        Canada_EastSaskatchewan,
        [RequestValue("Canada/Eastern")]
        Canada_Eastern,
        [RequestValue("Canada/Mountain")]
        Canada_Mountain,
        [RequestValue("Canada/Newfoundland")]
        Canada_Newfoundland,
        [RequestValue("Canada/Pacific")]
        Canada_Pacific,
        [RequestValue("Canada/Saskatchewan")]
        Canada_Saskatchewan,
        [RequestValue("Canada/Yukon")]
        Canada_Yukon,
        [RequestValue("Chile/Continental")]
        Chile_Continental,
        [RequestValue("Chile/EasterIsland")]
        Chile_EasterIsland,
        [RequestValue("Cuba")]
        Cuba,
        [RequestValue("EET")]
        EET,
        [RequestValue("EST")]
        EST,
        [RequestValue("EST5EDT")]
        EST5EDT,
        [RequestValue("Egypt")]
        Egypt,
        [RequestValue("Eire")]
        Eire,
        [RequestValue("Etc/GMT")]
        Etc_GMT,
        [RequestValue("Etc/GMT+0")]
        Etc_GMTp0,
        [RequestValue("Etc/GMT+1")]
        Etc_GMTp1,
        [RequestValue("Etc/GMT+10")]
        Etc_GMTp10,
        [RequestValue("Etc/GMT+11")]
        Etc_GMTp11,
        [RequestValue("Etc/GMT+12")]
        Etc_GMTp12,
        [RequestValue("Etc/GMT+2")]
        Etc_GMTp2,
        [RequestValue("Etc/GMT+3")]
        Etc_GMTp3,
        [RequestValue("Etc/GMT+4")]
        Etc_GMTp4,
        [RequestValue("Etc/GMT+5")]
        Etc_GMTp5,
        [RequestValue("Etc/GMT+6")]
        Etc_GMTp6,
        [RequestValue("Etc/GMT+7")]
        Etc_GMTp7,
        [RequestValue("Etc/GMT+8")]
        Etc_GMTp8,
        [RequestValue("Etc/GMT+9")]
        Etc_GMTp9,
        [RequestValue("Etc/GMT-1")]
        Etc_GMTm1,
        [RequestValue("Etc/GMT-10")]
        Etc_GMTm10,
        [RequestValue("Etc/GMT-11")]
        Etc_GMTm11,
        [RequestValue("Etc/GMT-12")]
        Etc_GMTm12,
        [RequestValue("Etc/GMT-13")]
        Etc_GMTm13,
        [RequestValue("Etc/GMT-14")]
        Etc_GMTm14,
        [RequestValue("Etc/GMT-2")]
        Etc_GMTm2,
        [RequestValue("Etc/GMT-3")]
        Etc_GMTm3,
        [RequestValue("Etc/GMT-4")]
        Etc_GMTm4,
        [RequestValue("Etc/GMT-5")]
        Etc_GMTm5,
        [RequestValue("Etc/GMT-6")]
        Etc_GMTm6,
        [RequestValue("Etc/GMT-7")]
        Etc_GMTm7,
        [RequestValue("Etc/GMT-8")]
        Etc_GMTm8,
        [RequestValue("Etc/GMT-9")]
        Etc_GMTm9,
        [RequestValue("Etc/GMT0")]
        Etc_GMT0,
        [RequestValue("Etc/Greenwich")]
        Etc_Greenwich,
        [RequestValue("Etc/UCT")]
        Etc_UCT,
        [RequestValue("Etc/Universal")]
        Etc_Universal,
        [RequestValue("Etc/Zulu")]
        Etc_Zulu,
        [RequestValue("Europe/Amsterdam")]
        Europe_Amsterdam,
        [RequestValue("Europe/Andorra")]
        Europe_Andorra,
        [RequestValue("Europe/Athens")]
        Europe_Athens,
        [RequestValue("Europe/Belfast")]
        Europe_Belfast,
        [RequestValue("Europe/Belgrade")]
        Europe_Belgrade,
        [RequestValue("Europe/Berlin")]
        Europe_Berlin,
        [RequestValue("Europe/Bratislava")]
        Europe_Bratislava,
        [RequestValue("Europe/Brussels")]
        Europe_Brussels,
        [RequestValue("Europe/Bucharest")]
        Europe_Bucharest,
        [RequestValue("Europe/Budapest")]
        Europe_Budapest,
        [RequestValue("Europe/Chisinau")]
        Europe_Chisinau,
        [RequestValue("Europe/Copenhagen")]
        Europe_Copenhagen,
        [RequestValue("Europe/Dublin")]
        Europe_Dublin,
        [RequestValue("Europe/Gibraltar")]
        Europe_Gibraltar,
        [RequestValue("Europe/Helsinki")]
        Europe_Helsinki,
        [RequestValue("Europe/Istanbul")]
        Europe_Istanbul,
        [RequestValue("Europe/Kaliningrad")]
        Europe_Kaliningrad,
        [RequestValue("Europe/Kiev")]
        Europe_Kiev,
        [RequestValue("Europe/Lisbon")]
        Europe_Lisbon,
        [RequestValue("Europe/Ljubljana")]
        Europe_Ljubljana,
        [RequestValue("Europe/London")]
        Europe_London,
        [RequestValue("Europe/Luxembourg")]
        Europe_Luxembourg,
        [RequestValue("Europe/Madrid")]
        Europe_Madrid,
        [RequestValue("Europe/Malta")]
        Europe_Malta,
        [RequestValue("Europe/Minsk")]
        Europe_Minsk,
        [RequestValue("Europe/Monaco")]
        Europe_Monaco,
        [RequestValue("Europe/Moscow")]
        Europe_Moscow,
        [RequestValue("Europe/Nicosia")]
        Europe_Nicosia,
        [RequestValue("Europe/Oslo")]
        Europe_Oslo,
        [RequestValue("Europe/Paris")]
        Europe_Paris,
        [RequestValue("Europe/Prague")]
        Europe_Prague,
        [RequestValue("Europe/Riga")]
        Europe_Riga,
        [RequestValue("Europe/Rome")]
        Europe_Rome,
        [RequestValue("Europe/Samara")]
        Europe_Samara,
        [RequestValue("Europe/San_Marino")]
        Europe_San_Marino,
        [RequestValue("Europe/Sarajevo")]
        Europe_Sarajevo,
        [RequestValue("Europe/Simferopol")]
        Europe_Simferopol,
        [RequestValue("Europe/Skopje")]
        Europe_Skopje,
        [RequestValue("Europe/Sofia")]
        Europe_Sofia,
        [RequestValue("Europe/Stockholm")]
        Europe_Stockholm,
        [RequestValue("Europe/Tallinn")]
        Europe_Tallinn,
        [RequestValue("Europe/Tirane")]
        Europe_Tirane,
        [RequestValue("Europe/Tiraspol")]
        Europe_Tiraspol,
        [RequestValue("Europe/Uzhgorod")]
        Europe_Uzhgorod,
        [RequestValue("Europe/Vaduz")]
        Europe_Vaduz,
        [RequestValue("Europe/Vatican")]
        Europe_Vatican,
        [RequestValue("Europe/Vienna")]
        Europe_Vienna,
        [RequestValue("Europe/Vilnius")]
        Europe_Vilnius,
        [RequestValue("Europe/Warsaw")]
        Europe_Warsaw,
        [RequestValue("Europe/Zagreb")]
        Europe_Zagreb,
        [RequestValue("Europe/Zaporozhye")]
        Europe_Zaporozhye,
        [RequestValue("Europe/Zurich")]
        Europe_Zurich,
        [RequestValue("Factory")]
        Factory,
        [RequestValue("GB")]
        GB,
        [RequestValue("GB-Eire")]
        GBEire,
        [RequestValue("GMT")]
        GMT,
        [RequestValue("GMT+0")]
        GMTp0,
        [RequestValue("GMT-0")]
        GMTm0,
        [RequestValue("GMT0")]
        GMT0,
        [RequestValue("Greenwich")]
        Greenwich,
        [RequestValue("HST")]
        HST,
        [RequestValue("Hongkong")]
        Hongkong,
        [RequestValue("Iceland")]
        Iceland,
        [RequestValue("Indian/Antananarivo")]
        Indian_Antananarivo,
        [RequestValue("Indian/Chagos")]
        Indian_Chagos,
        [RequestValue("Indian/Christmas")]
        Indian_Christmas,
        [RequestValue("Indian/Cocos")]
        Indian_Cocos,
        [RequestValue("Indian/Comoro")]
        Indian_Comoro,
        [RequestValue("Indian/Kerguelen")]
        Indian_Kerguelen,
        [RequestValue("Indian/Mahe")]
        Indian_Mahe,
        [RequestValue("Indian/Maldives")]
        Indian_Maldives,
        [RequestValue("Indian/Mauritius")]
        Indian_Mauritius,
        [RequestValue("Indian/Mayotte")]
        Indian_Mayotte,
        [RequestValue("Indian/Reunion")]
        Indian_Reunion,
        [RequestValue("Iran")]
        Iran,
        [RequestValue("Israel")]
        Israel,
        [RequestValue("Jamaica")]
        Jamaica,
        [RequestValue("Japan")]
        Japan,
        [RequestValue("Kwajalein")]
        Kwajalein,
        [RequestValue("Libya")]
        Libya,
        [RequestValue("MET")]
        MET,
        [RequestValue("MST")]
        MST,
        [RequestValue("MST7MDT")]
        MST7MDT,
        [RequestValue("Mexico/BajaNorte")]
        Mexico_BajaNorte,
        [RequestValue("Mexico/BajaSur")]
        Mexico_BajaSur,
        [RequestValue("Mexico/General")]
        Mexico_General,
        [RequestValue("Mideast/Riyadh87")]
        Mideast_Riyadh87,
        [RequestValue("Mideast/Riyadh88")]
        Mideast_Riyadh88,
        [RequestValue("Mideast/Riyadh89")]
        Mideast_Riyadh89,
        [RequestValue("NZ")]
        NZ,
        [RequestValue("NZ-CHAT")]
        NZCHAT,
        [RequestValue("Navajo")]
        Navajo,
        [RequestValue("PRC")]
        PRC,
        [RequestValue("PST8PDT")]
        PST8PDT,
        [RequestValue("Pacific/Apia")]
        Pacific_Apia,
        [RequestValue("Pacific/Auckland")]
        Pacific_Auckland,
        [RequestValue("Pacific/Chatham")]
        Pacific_Chatham,
        [RequestValue("Pacific/Easter")]
        Pacific_Easter,
        [RequestValue("Pacific/Efate")]
        Pacific_Efate,
        [RequestValue("Pacific/Enderbury")]
        Pacific_Enderbury,
        [RequestValue("Pacific/Fakaofo")]
        Pacific_Fakaofo,
        [RequestValue("Pacific/Fiji")]
        Pacific_Fiji,
        [RequestValue("Pacific/Funafuti")]
        Pacific_Funafuti,
        [RequestValue("Pacific/Galapagos")]
        Pacific_Galapagos,
        [RequestValue("Pacific/Gambier")]
        Pacific_Gambier,
        [RequestValue("Pacific/Guadalcanal")]
        Pacific_Guadalcanal,
        [RequestValue("Pacific/Guam")]
        Pacific_Guam,
        [RequestValue("Pacific/Honolulu")]
        Pacific_Honolulu,
        [RequestValue("Pacific/Johnston")]
        Pacific_Johnston,
        [RequestValue("Pacific/Kiritimati")]
        Pacific_Kiritimati,
        [RequestValue("Pacific/Kosrae")]
        Pacific_Kosrae,
        [RequestValue("Pacific/Kwajalein")]
        Pacific_Kwajalein,
        [RequestValue("Pacific/Majuro")]
        Pacific_Majuro,
        [RequestValue("Pacific/Marquesas")]
        Pacific_Marquesas,
        [RequestValue("Pacific/Midway")]
        Pacific_Midway,
        [RequestValue("Pacific/Nauru")]
        Pacific_Nauru,
        [RequestValue("Pacific/Niue")]
        Pacific_Niue,
        [RequestValue("Pacific/Norfolk")]
        Pacific_Norfolk,
        [RequestValue("Pacific/Noumea")]
        Pacific_Noumea,
        [RequestValue("Pacific/Pago_Pago")]
        Pacific_Pago_Pago,
        [RequestValue("Pacific/Palau")]
        Pacific_Palau,
        [RequestValue("Pacific/Pitcairn")]
        Pacific_Pitcairn,
        [RequestValue("Pacific/Ponape")]
        Pacific_Ponape,
        [RequestValue("Pacific/Port_Moresby")]
        Pacific_Port_Moresby,
        [RequestValue("Pacific/Rarotonga")]
        Pacific_Rarotonga,
        [RequestValue("Pacific/Saipan")]
        Pacific_Saipan,
        [RequestValue("Pacific/Samoa")]
        Pacific_Samoa,
        [RequestValue("Pacific/Tahiti")]
        Pacific_Tahiti,
        [RequestValue("Pacific/Tarawa")]
        Pacific_Tarawa,
        [RequestValue("Pacific/Tongatapu")]
        Pacific_Tongatapu,
        [RequestValue("Pacific/Truk")]
        Pacific_Truk,
        [RequestValue("Pacific/Wake")]
        Pacific_Wake,
        [RequestValue("Pacific/Wallis")]
        Pacific_Wallis,
        [RequestValue("Pacific/Yap")]
        Pacific_Yap,
        [RequestValue("Poland")]
        Poland,
        [RequestValue("Portugal")]
        Portugal,
        [RequestValue("ROC")]
        ROC,
        [RequestValue("ROK")]
        ROK,
        [RequestValue("Singapore")]
        Singapore,
        [RequestValue("SystemV/AST4")]
        SystemV_AST4,
        [RequestValue("SystemV/AST4ADT")]
        SystemV_AST4ADT,
        [RequestValue("SystemV/CST6")]
        SystemV_CST6,
        [RequestValue("SystemV/CST6CDT")]
        SystemV_CST6CDT,
        [RequestValue("SystemV/EST5")]
        SystemV_EST5,
        [RequestValue("SystemV/EST5EDT")]
        SystemV_EST5EDT,
        [RequestValue("SystemV/HST10")]
        SystemV_HST10,
        [RequestValue("SystemV/MST7")]
        SystemV_MST7,
        [RequestValue("SystemV/MST7MDT")]
        SystemV_MST7MDT,
        [RequestValue("SystemV/PST8")]
        SystemV_PST8,
        [RequestValue("SystemV/PST8PDT")]
        SystemV_PST8PDT,
        [RequestValue("SystemV/YST9")]
        SystemV_YST9,
        [RequestValue("SystemV/YST9YDT")]
        SystemV_YST9YDT,
        [RequestValue("Turkey")]
        Turkey,
        [RequestValue("UCT")]
        UCT,
        [RequestValue("US/Alaska")]
        US_Alaska,
        [RequestValue("US/Aleutian")]
        US_Aleutian,
        [RequestValue("US/Arizona")]
        US_Arizona,
        [RequestValue("US/Central")]
        US_Central,
        [RequestValue("US/East-Indiana")]
        US_EastIndiana,
        [RequestValue("US/Eastern")]
        US_Eastern,
        [RequestValue("US/Hawaii")]
        US_Hawaii,
        [RequestValue("US/Indiana-Starke")]
        US_IndianaStarke,
        [RequestValue("US/Michigan")]
        US_Michigan,
        [RequestValue("US/Mountain")]
        US_Mountain,
        [RequestValue("US/Pacific")]
        US_Pacific,
        [RequestValue("US/Pacific-New")]
        US_PacificNew,
        [RequestValue("US/Samoa")]
        US_Samoa,
        [RequestValue("UTC")]
        UTC,
        [RequestValue("Universal")]
        Universal,
        [RequestValue("W-SU")]
        WSU,
        [RequestValue("WET")]
        WET,
        [RequestValue("Zulu")]
        Zulu
    }

    public enum GenericSort
    {
        [RequestValue("asc")]
        Ascending,
        [RequestValue("desc")]
        Descending
    }

    public enum CommentObjectType
    {
        [RequestValue("")]
        Empty,
        [RequestValue("photo")]
        Photo,
        [RequestValue("album")]
        Album
    }
}